plugins:
  creem_enabled:
    default: false
    client: true
  creem_test_mode:
    default: true
    client: true
  creem_api_key:
    default: ""
    secret: true
  creem_webhook_secret:
    default: ""
    secret: true
  creem_product_id:
    default: ""
    client: true
  creem_subscription_group:
    default: ""
    type: group
